# Generated by Django 5.2.4 on 2025-10-29 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_artigo_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
